<a href="https://colab.research.google.com/github/mishrapranjal879/PythonCodesForPractice/blob/main/Pandas_Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [1]:
import numpy as np
import pandas as pd

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [9]:
a = [10,20,30,40]
s = pd.Series(a,name = "marks")
d = {"Pranjal":90,"Siddhant":85,"Ketan":76,"Deepak":34}
s2 = pd.Series(d,name = "marks")

print(s2)

Pranjal     90
Siddhant    85
Ketan       76
Deepak      34
Name: marks, dtype: int64

### Creating a DataFrame

In [11]:
a = {
    "Name": ["Pranjal","Siddhant","Deepak","Ketan"],
    "Marks": [90,85,78,86],
    "Subject": ["Math","Science","History","English"]
}
pd.DataFrame(a)

       Name  Marks  Subject
0   Pranjal     90     Math
1  Siddhant     85  Science
2    Deepak     78  History
3     Ketan     86  English


### Creating DataFrame from NumPy Arrays

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
pd.DataFrame(a,columns = ["A","B","C"])

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.